### PR TITLE
🎨 Refactor: Targeting

### PR DESCRIPTION
**Pull request by Rav3n95**
- Added DrawSprite option
- Utilised statebag
- Made minor performance update
- Removed unused Logger module

### CODE REVIEW

**Comment by Rav3n95** [comment]
- Optimised threads on Police module

**Comment by Rav3n95** [comment]
- `isNearTrunk` function is replaced with `IsNearTrunk`

**Comment by Rav3n95** [comment]
- Changed LocalPlayer.state.PlayerID to LocalPlayer.state.clientID
- Changed LocalPlayer.state.myPos to LocalPlayer.state.position
- Added: LocalPlayer.state.serverID

Statebags we can use now:

- LocalPlayer.state.ped --> Return the player ped
- LocalPlayer.state.position --> Return the player position on vector3
- LocalPlayer.state.clientID --> Return the player client id
- LocalPlayer.state.serverID --> Return the player server id

**Comment by Aspect06** [comment]
yo what you sayin

**Pull request merged**
