### PR TITLE
(Queue) Fixed Delay shit

### PR DESCRIPTION
**Pull request by elijahdeveloperinc**

### CODE REVIEW

**Comment by Rav3n95** [comment]
Why would you remove it?

**Comment by Sampuke** [comment]
There is nothing to be fixed. Enable dev mode if it's a problem

**Comment by Boom1053** [comment]
some people don't think of commenting stuff out instead of just deleting shit o.0

**Comment by aka-lucifer** [comment]
Nothing to fix, you can simply comment it out if you don't want it.

**Pull request closed without merging**
